# fly.toml app configuration file generated for tata1mg-patient-dashboard on 2024-10-06T21:21:14+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tata1mg-patient-dashboard'

[build]

[http_service]
  internal_port = 3005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  http_checks = []
  internal_port = 3005
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
